version: '2'
services:
  tests:
    image: buildkite/plugin-tester
    volumes:
      - ".:/plugin:ro"

  lint:
    image: buildkite/plugin-linter
    command: ['--id', 'thilinaperera/gcp-secret-to-file']
    volumes:
      - ".:/plugin:ro"

  shellcheck:
    image: koalaman/shellcheck-alpine:latest
    command: ['shellcheck', '/plugin/hooks/environment']
    volumes:
      - ".:/plugin:ro"
